---
- name: Create a login user
  user:
    createhome: true
    groups: sudo
    home: "/home/{{ user_name }}"
    name: "{{ user_name }}"
    shell: /bin/bash
    state: present
    system: false
  tags:
    - users_add
- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="#PasswordAuthentication yes" line="PasswordAuthentication no" state=present
  notify:
    - ssh restart
